### ISSUE TITLE
Add a `PeriodicFeatureExtractor`

### ISSUE THREAD

**Issue by matthias-wende-frequenz** [frequenz-floss/frequenz-sdk-python#120] opened 2022-12-14 13:00 UTC
### What's needed?

For forecasting we have been using average load and production profiles. 

Given a time series, we want a module that is able to calculate the item wise average of repeating time windows of the same size and the same sample-rate, possibly all having the same distance.

**Example:**

Consider the time series $T = [1,2,3,4,5,6,7,8,9,1]$ and a window a length $2$ with distance $2$ starting at the first position.

Hence we get the sub-series $t_1=[1,2], t_2=[5,6], t_3=[9,1]$ and therefore the average $$t_{avg}=[(1+5+9)/3, (2+6+1)/3] = [5, 3]$$

*Note*: A position could likewise be a timestamp in a usual time-series representation.

### Proposed solution

We want to design such a module in a way such that it

* uses batches of data (most likely cached in memory)
* is designed to work together with the data structure defined [here](https://github.com/frequenz-floss/frequenz-sdk-python/issues/113)
* it should be able to run calculations on demand and memoize the result

### Use cases

It's been used for calculating average load and production profiles certain days.
For example it could just calculate the average load of some consume of the last seven days as well as the average PV production of the last four Tuesdays.

### Alternatives and workarounds

It's possible to run the calculation and update the mean on a data stream whenever a new sample arrives. However we plan on storing batches of data in any case, as this can be used as a feature for ml models, and thus calculating the averages from the batches seems obvious.
Additionally this option hasn't been further explored so far.

### Additional context

We have had a use-case where we where looking at a full days averaged data plus a 15 minute [margin](https://github.com/frequenz-floss/frequenz-sdk-python/issues/120#issuecomment-1359587158). Thus we will need to add a margin for a window size in order to re-engineer this feature.

**Comment by mathias-baumann-frequenz** [comment] 2022-12-20 09:26
We'll probably be able to use https://numpy.org/doc/stable/reference/generated/numpy.lib.stride_tricks.as_strided.html#numpy.lib.stride_tricks.as_strided for accessing arrays in strides in numpy

possilby helpful: https://numpy.org/doc/stable/reference/generated/numpy.mean.html

**Comment by matthias-wende-frequenz** [comment] 2022-12-20 15:42
We need a margin around the window, such that we can say we want a specific load profile of a certain weekday +-15min. That would translate to the following parameters:

```
window_size = 1day
distance = 6days
margin = 15min
```

We could also consider introducing independent left and right margins.

Note: maybe we want padding (the one that goes to the outside)

**Comment by matthias-wende-frequenz** [comment] 2022-12-21 09:04
> possilby helpful: [numpy.org/doc/stable/reference/generated/numpy.mean.html](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)

Indeed useful. We can `reshape` the array into an 2 dimensional first and use the `where` array to select which values to include, i.e. leaf out all values that are not in any window or window margin. Using numpy's internal functions is likely faster then iterating over the values in python for calculating the mean.

**Comment by matthias-wende-frequenz** [comment] 2022-12-22 15:37
**Note**: Average Time Series can be empty or a series of zeros because there is not enough data existing in the buffer or the buffer is full of NaN or in case the averaging calculation hasn't finished in time.

**Comment by matthias-wende-frequenz** [comment] 2022-12-22 16:06
Should be able to calculate mean, standard deviation and polynomial coefficients.

**Comment by thomas-nicolai-frequenz** [comment] 2022-12-27 19:04
It is important to note that the TimeseriesAverageCalculator takes the samples from the SlidingWindowOperator / StreamBucketOperator and computes the averages from that. The structure of the resulting static array should be defined in the constructor to make sure this can't be changed at runtime. 

We should also give an example on how this the TimeseriesAverageCalculator calculation can be invoked in a memoized fashion e.g. if the calculation hasn't been updated since a certain amount of time or if a new day has arrived. Please be aware of time zones.

**Comment by david-natingga-frequenz** [comment] 2023-01-04 07:50
For your information, aggregate functions over **windows of varying size** may be useful. For example, for frequency forecast, some of the most important features include mean over the last _30 seconds_ of data, and other means over _15 minutes_ of data.

**Comment by thomas-nicolai-frequenz** [comment] 2023-01-04 08:23
> For example, for frequency forecast, some of the most important features include mean over the last 30 seconds of data, and other means over 15 minutes of data.

sure. thats no problem and does not speak against using a fixed buffer size. if someone is only interested into parts of the data in the buffer thats fine. we have accounted for that use case as for example this is required for the peak shaving.

**Comment by idlir-shkurti-frequenz** [comment] 2023-01-10 14:51
Say in this example that was mentioned above:

```
window_size = 1day
distance = 6days
margin = 15min
```

I am assuming this takes the window of 1 day starting from the point in time when the `TimeseriesAverageCalculator` is ran, right? So if I want the average of a specific weekday then I should run this just after the end of that day? Is that the idea?

**Comment by idlir-shkurti-frequenz** [comment] 2023-01-10 14:52
Also just to clarify. If we want the data at a specific sampling rate this is taken care of [here](https://github.com/frequenz-floss/frequenz-sdk-python/issues/113), right?

**Comment by matthias-wende-frequenz** [comment] 2023-01-25 11:04
> Say in this example that was mentioned above:
> 
> window_size = 1day
> distance = 6days
> margin = 15min
> 
> I am assuming this takes the window of 1 day starting from the point in time when the TimeseriesAverageCalculator is ran, right? So if I want the average of a specific weekday then I should run this just after the end of that day? Is that the idea?

That depends. The `MovingWindow` can be aligned to start at a certain point in time. This module will have an offset. So if e.g. you store 29days of data that is aligned to start on Monday then you can set the offset to 2 days and get the profile for Wednesdays.

**Comment by cwasicki** [comment] 2023-04-05 15:13
Some notes from today's meeting (and from #299):

* Maybe something like `LagWindow` would be a better name (see https://en.wikipedia.org/wiki/Lag_operator)? 
* In future we would also need other metrics like e.g. `min`, `max`, `std`.
* Some use-cases could include:
  * Maximum value for the upcoming 15min time period for the same weekday in the last 28 days.
  * Average value for the 1h time period 2h in the future for the last 5 days.
  * Standard deviation for the 1h time period 23h in the future over the last 28 days. 
* @idlir-shkurti-frequenz  and @cwasicki will propose some unit tests for our use cases.
* Can it be used directly with numpy arrays instead of moving window?
* Does it make sense to also provide a step-wise definition of the window in addition to use datetimes?
* Instead of creating multiple objects with different distances, it could be advantageous to work with weights of zero to select a sub-range.
* What's the (desired) behaviour if the window is incomplete?

@matthias-wende-frequenz @idlir-shkurti-frequenz Anything to add?

**Comment by thomas-nicolai-frequenz** [comment] 2023-04-05 17:50
> In future we would also need other metrics like e.g. min, max, std.

@matthias-wende-frequenz this should be pretty straight forward to implement right? can you create a seperate issue for that once the PR is merged?

> Can it be used directly with numpy arrays instead of moving window?

@cwasicki what would be the use case?

> Does it make sense to also provide a step-wise definition of the window in addition to use datetimes?

@cwasicki If there are not dates what is the point of reference? Everything is based on timestamps.... how would that work?

> What's the (desired) behaviour if the window is incomplete?

@cwasicki what is an incomplete window? like when the app starts and there is not enough data yet to create the averages? what has this to do with the MovingWindow? Sounds like like an upstream problem imho

**Comment by cwasicki** [comment] 2023-04-05 19:32
> @cwasicki what would be the use case?

We could use it for feature generation on data frames for example and use it now already.




> @cwasicki If there are not dates what is the point of reference? Everything is based on timestamps.... how would that work?

If you work equidistantly sampled data you could easily reference N time steps ahead.




> @cwasicki what is an incomplete window? like when the app starts and there is not enough data yet to create the averages? what has this to do with the MovingWindow? Sounds like like an upstream problem imho

Yes, if you don't have enough data. For instance, what is the expected behaviour in case we want a last 4 same weekdays average on a completely new site? First week you have no data, next three weeks you still have less than the 4 days you asked for. Options could be to just use any data that is available (and maybe warn), return None or throw an exception. I would prefer the first option. But it also depends on the implementation since the `weights` may not match anymore.

**Comment by thomas-nicolai-frequenz** [comment] 2023-04-06 08:47
> We could use it for feature generation on data frames for example and use it now already.

Right so, if you replace the MovingWindow with a numpy array you essentially just pumping all data thats coming out of the Resampler into memory. So is the use case about model training? Can you please give some more precise examples/explanation, please :-)

**Comment by thomas-nicolai-frequenz** [comment] 2023-04-06 08:51
> Yes, if you don't have enough data. For instance, what is the expected behaviour in case we want a last 4 same weekdays average on a completely new site

Thats not a question about the MovingWindow but rather application level of what the fallback behaviour would/should look like. Can you put that on the DS agenda?

**Comment by cwasicki** [comment] 2023-04-06 11:12
> Right so, if you replace the MovingWindow with a numpy array you essentially just pumping all data thats coming out of the Resampler into memory. So is the use case about model training? Can you please give some more precise examples/explanation, please :-)

Yes, it's about model training. We are using data frames for this, so essentially numpy arrays. If it's possible we could apply only the TimeSeriesAverager from the SDK already now for creating features on our training data. Example could look like:

```
def tsavg(pd_series):
    # Code using TimeSeriesAverager with a pandas Series or numpy array
    ...
    return avg

# Calling tsavg over a 7 day rolling window in a pandas data frame
df.roll("7D")["some_column"].apply(tsavg) 
```



> Thats not a question about the MovingWindow but rather application level of what the fallback behaviour would/should look like. Can you put that on the DS agenda?

Sure, the application should always be responsible how this is handled. There should still be a clearly defined behaviour of the TimeSeriesAverager in this case. Added it to the agenda.

**Comment by matthias-wende-frequenz** [comment] 2023-04-06 14:01
> In future we would also need other metrics like e.g. min, max, std.
>> @matthias-wende-frequenz this should be pretty straight forward to implement right? can you >> create a seperate issue for that once the PR is merged?

@cwasicki can you please define what you mean by min, max, std in this context?

**Comment by cwasicki** [comment] 2023-04-06 14:54
> @cwasicki can you please define what you mean by min, max, std in this context?

For the TimeSeriesAverager you select a subset of the moving window and then take the average of these values. Similarly, you could also get the maximum, minimum or standard deviation on this subset. For instance, what was the maximum value in a specific time period of the day over the last 7 days.

**Comment by thomas-nicolai-frequenz** [comment] 2023-04-08 18:02
> can you please define what you mean by min, max, std in this context

@cwasicki is that the min, max and std of the averaged timeseries or the underlying MovingWindow? @matthias-wende-frequenz that indeed raises a good question if renaming the TimeseriesAverager to MovingWindowAverager is really to way to go. At the very end the derived timeseries isn't really anymore connected the the MovingWindow itself that contains raw data whereas the TimeseriesAvergager contains derived statistical measures from the MovingWindow.

**Comment by cwasicki** [comment] 2023-04-11 12:27
>@cwasicki is that the min, max and std of the averaged timeseries or the underlying MovingWindow?

I meant the underlying moving window. To clarify with an example: Assuming it's 15:00. Based on a time series window with data points every 15 min for the last 28 days, if you want to have the minimum for a time period of today 10:00 - 10:30 (i.e. two data points) and a distance of 7 days (i.e. 4 times a window with 2 data points) you would receive two values. The first value is the minimum value of the four values of 10:00-10:15 data points today, 7, 14 and 21 days ago. Equivalently you determine the second value, but for the 10:15-10:30 data points instead.

**Comment by cwasicki** [comment] 2023-04-11 12:40
A potential use-case could be for a PV forecast: the production of a recent sunny day gives you at least some indication of the potential of your PV system for the given time period. You can get some estimate by taking the maximum of that time period over the last couple of days. In contrast to that, the production on cloudy days don't tell you much about the future unless you combine it with very good weather forecast data.

**Closed as completed** 2023-06-02 10:23 UTC
Labels: priority:high, type:enhancement, part:data-pipeline
