### ISSUE TITLE
Use inverter data if inverter meter is down for grid load calculation

### ISSUE THREAD

**Issue by idlir-shkurti-frequenz** [frequenz-floss/frequenz-sdk-python#294] opened 2023-03-30 13:26 UTC
### What's needed?

Currently the grid load is calculated by adding up all the relevant meters in the microgrid. If any of the meters is down then the `grid_load()` formula gives out None. This means that even if one of the inverter meters is down but the inverter still working, then the grid load will return a None value. The `battery_power()` function on the other hand will not return `None` as this function gets its power data from the inverters.

### Proposed solution

Use the inverters as back up to get the inverter/battery load if any inverter meter goes down. This will require changes to the `grid_load()` function.

### Use cases

If the main meter is not working properly, then a `None` grid load value is expected from peak shaving. This will mean that peak shaving will go into slow discharge mode. However if one of the inverter meters is also down peak shaving will also go into slow discharge mode even though the inverters/batteries are working correctly.

**Comment by llucax** [comment] 2024-08-07 07:17
Duplicate of #184

**Closed as not planned by llucax** 2024-08-07 07:17 UTC
Labels: resolution:duplicate, type:enhancement, part:data-pipeline
